[pattern.weave]
targets = ["site/{basename}.html"]
dependencies = ["docs/{basename}.md"]
language = "Python"
script = """
import subprocess
from pathlib import Path

output_type = "html5"
lua_filters = ["annotate"]
input_dir = Path("docs")
output_dir = Path("site")

scripts = Path(".entangled/scripts")
lua_filter_scripts = [scripts / f"{{lf}}.lua" for lf in lua_filters]

output_dir.mkdir(exist_ok=True, parents=True)
output_file = output_dir / "{basename}.html"
input_file = input_dir / "{basename}.md"

pandoc_args  = [ "pandoc", "-t", output_type, "-s" ]
for lf in lua_filter_scripts:
    pandoc_args += [ "--lua-filter", str(lf) ]
pandoc_args += [ "-o", str(output_file) ]
pandoc_args += [ str(input_file) ]

subprocess.run(pandoc_args)
"""

